### PR TITLE
NSIS: Don't restart on kernel update when interactive

### LINKED ISSUE #282: Installer reboots Windows without warning
I ran the latest installer on a Windows Pro machine that already had WSL2, Docker Desktop, Ubuntu and openSUSE distros installed.

I got the UAC prompt asking me if I want to let the installer modify my Windows settings, which I confirmed. After a little while it automatically rebooted the VM without asking for confirmation.

1. I don't understand why it had to reboot the machine, as WSL2 was already installed.
2. We should *never* reboot a machine without getting explicit user confirmation first.

I've uninstalled and reinstalled Rancher Desktop, but could no longer repro the reboot behaviour. I may fetch a copy of last night's backup to see if I can repro there.

Also noticed that uninstall doesn't actually remove the RD data, which can be much larger than the app itself (the cached k3s versions plus container images).

### PR DESCRIPTION
**Pull request by mook-as**
If the user had already installed WSL, but _not_ the kernel update, we should not force a reboot; instead, we should prompt the user first.

Also remove logging that wasn't meant to be checked in.

Fixes #282

### CODE REVIEW

**Review by mattfarina — CHANGES_REQUESTED** [review]
I just tried this and I was not prompted. I've not dug into why but the second reboot was automatic and had no notice.

**Comment by mook-as** [comment]
_Having_ a second reboot is expected, as long as it happens right after the first one.  Previously, it _never_ prompted when you only needed the second reboot, which was bad.

**Comment by mattfarina** [comment]
@mook-as I'll test that situation Friday morning.

**Review by ericpromislow — APPROVED** [review]
Approving with a note: the scope of this PR is not to restart on kernel update, but it would be nice if instead of saying `A WIndows restart is required`, it would be easier on the user to ask them if they'd like to reboot now, or manually reboot later.

**Comment by mook-as** [comment]
That message is just for logging — the exit code means the installer sees it and shows the same restart prompt as the case where WSL wasn't previously installed.
image

**Comment by jandubois** [comment]
I confirm that with the change I get the messagebox shown above after just upgrading the kernel.

**Review by jandubois — APPROVED** [review]

**Review by mattfarina — APPROVED** [review]

**Pull request merged**
