### PR TITLE
Issue 121 - pristine machine: squelch error dialog

### PR DESCRIPTION
**Pull request by ericpromislow**
Don't complain if there's an error trying to stop minikube if it couldn't be started

### CODE REVIEW

**Review by mook-as — COMMENTED** [review]
Doesn't this mean that if the VM gets wedged in an error state, we'll never let the user know they need to manually fix things?

**Comment by ericpromislow** [comment]
Let me make sure they would have seen one error message already.

**Comment by mattfarina** [comment]
@ericpromislow minikube is used internally. Once you run `npm run setupmac` minikube is installed. And it's bundled in the build of rd. Error stopping minikube is from our internal use of it.

**Comment by ericpromislow** [comment]
ok, dropping this PR

**Pull request closed without merging**
