### PR TITLE
Updating the icons and build application name

### LINKED ISSUE #188: Update Electron Icon and Name
The name of the output application should be "Rancher Desktop" and the icon should be the new logo

### PR DESCRIPTION
**Pull request by mattfarina**
Closes #188

### CODE REVIEW

**Comment by mattfarina** [comment]
Screen Shot 2021-04-23 at 4 30 31 PM

**Review by mook-as — COMMENTED** [review]
Is it just me, or is `logo-square-bw@1.5x.png` kind of off? Same with `@2`? Like, not square?

**Comment by mattfarina** [comment]
The icon is rectangle sitting in a square space. When it's 32px wide it's about 18.5px tall but centered on 32px tall. This is the design from Lauren.

I see the issue with the packaging script and I'll come back to fix it.

**Comment by mook-as** [comment]
Right, but the image itself should still be square (with transparent top & bottom), right? Currently the 1.5 is 24px × 14px I think?

**Comment by ericpromislow** [comment]
Should the image in the header bar be the new PC with horns instead of the current cow/bull?

**Comment by ericpromislow** [comment]
The CI windows package test is failing because `rancher-desktop.exe` is in `dist/win-unpacked` - will that fix the action?

**Comment by mattfarina** [comment]
@mook-as thanks for catching the mis-shaped icon. Fixed.

@ericpromislow it was failing because the file is now "Rancher Desktop.exe" instead. Different naming pattern. Fixed now.

**Comment by mattfarina** [comment]
This is ready for a re-review.

**Review by mook-as — CHANGES_REQUESTED** [review]
`resources/icons/logo-square-bw@2.png` still appears to be not-square (32x19).  Given the previous comment I assume this is unintended.

**Comment by ericpromislow** [comment]
Still using the old bull logo at the left end of the header bar -- don't know whether the PC image should replace this.

Everything else looks fine.

**Review by mook-as — APPROVED** [review]
LGTM. The tray icon is a bit harder to see on mac (because the slim blue line on a white-ish background is difficult to tell from the grey version), but we can iterate on that later.

**Pull request merged**
