### PR TITLE
Make `npm run dev` do something useful on Windows

### PR DESCRIPTION
**Pull request by mook-as**
This makes things mostly work on Windows for #15.  It is based on #160, and requires that to be merged first.

Main changes:

- `npm run setupmac`:
  - Make it run automatically after `npm install`.
  - Make it work on Windows (only downloading `kubectl` & `helm`).
  - Make the downloading less callback-heavy.
  - Make it use `node-fetch` rather than `follow-redirects`. (We already use both in dependencies.)
- Make `npm run dev` work on Windows (rather than dying)
- Kubernetes:
  - Implement WSL-based backend
    - Download the distro (from Jan) as needed
    - Download K3s as needed (following Jan's scripts)
      - The version is hard coded right now; fixing that will be in a follow-up PR.
    - Port forwarding _should_ be working
    - There's still an issue with certs, TBD; wanted to get this PR in first.
- Hide the VM sizing UI on Windows, since we can't (or at least shouldn't) adjust that here.

Marking this as draft until #160 is merged first.

### CODE REVIEW

**Comment by ericpromislow** [comment]
You'll need to decide what `script/hyperkit`'s extension is

**Comment by ericpromislow** [comment]
I can't get past this `npm i` error on windows:

```
3211 verbose stack Error: command failed
3211 verbose stack     at ChildProcess.<anonymous> (C:\Users\User\scoop\persist\nvm\nodejs\v15.14.0\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
3211 verbose stack     at ChildProcess.emit (node:events:369:20)
3211 verbose stack     at maybeClose (node:internal/child_process:1067:16)
3211 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
3212 verbose pkgid node-sass@4.14.1
3213 verbose cwd C:\Users\User\rd
3214 verbose Windows_NT 10.0.19042
3215 verbose argv "C:\\Users\\User\\scoop\\apps\\nvm\\current\\nodejs\\nodejs\\node.exe" "C:\\Users\\User\\scoop\\apps\\nvm\\current\\nodejs\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
3216 verbose node v15.14.0
3217 verbose npm  v7.8.0
3218 error code 1
3219 error path C:\Users\User\rd\node_modules\node-sass
3220 error command failed
3221 error command C:\Windows\system32\cmd.exe /d /s /c node scripts/build.js
3222 error Building: C:\Users\User\scoop\apps\nvm\current\nodejs\nodejs\node.exe C:\Users\User\rd\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
3223 error gyp info it worked if it ends with ok
3223 error gyp verb cli [
3223 error gyp verb cli   'C:\\Users\\User\\scoop\\apps\\nvm\\current\\nodejs\\nodejs\\node.exe',
3223 error gyp verb cli   'C:\\Users\\User\\rd\\node_modules\\node-gyp\\bin\\node-gyp.js',
3223 error gyp verb cli   'rebuild',
3223 error gyp verb cli   '--verbose',
3223 error gyp verb cli   '--libsass_ext=',
3223 error gyp verb cli   '--libsass_cflags=',
3223 error gyp verb cli   '--libsass_ldflags=',
3223 error gyp verb cli   '--libsass_library='
3223 error gyp verb cli ]
3223 error gyp info using node-gyp@3.8.0
3223 error gyp info using node@15.14.0 | win32 | x64
3223 error gyp verb command rebuild []
3223 error gyp verb command clean []
3223 error gyp verb clean removing "build" directory
3223 error gyp verb command configure []
3223 error gyp verb check python checking for Python executable "python2" in the PATH
3223 error gyp verb `which` succeeded python2 C:\Python27\python2.EXE
3223 error gyp verb check python version `C:\Python27\python2.EXE -c "import sys; print "2.7.18
3223 error gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
3223 error gyp verb get node dir no --target version specified, falling back to host node version: 15.14.0
3223 error gyp verb command install [ '15.14.0' ]
3223 error gyp verb install input version string "15.14.0"
3223 error gyp verb install installing version: 15.14.0
3223 error gyp verb install --ensure was passed, so won't reinstall if already installed
3223 error gyp verb install version is already installed, need to check "installVersion"
3223 error gyp verb got "installVersion" 9
3223 error gyp verb needs "installVersion" 9
3223 error gyp verb install version is good
3223 error gyp verb get node dir target node version installed: 15.14.0
3223 error gyp verb build dir attempting to create "build" dir: C:\Users\User\rd\node_modules\node-sass\build
3223 error gyp verb build dir "build" dir needed to be created? C:\Users\User\rd\node_modules\node-sass\build
3223 error gyp verb find vs2017 Found installation at: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
3223 error gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.VC.Tools.x86.x64
3223 error gyp verb find vs2017   - Found Microsoft.VisualStudio.VC.MSBuild.Base
3223 error gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.Windows10SDK.19041
3223 error gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.Windows10SDK.18362
3223 error gyp verb find vs2017   - Using this installation with Windows 10 SDK
3223 error gyp verb find vs2017 using installation: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
3223 error gyp verb build/config.gypi creating config file
3223 error gyp verb build/config.gypi writing out config file: C:\Users\User\rd\node_modules\node-sass\build\config.gypi
3223 error gyp verb config.gypi checking for gypi file: C:\Users\User\rd\node_modules\node-sass\config.gypi
3223 error gyp verb common.gypi checking for gypi file: C:\Users\User\rd\node_modules\node-sass\common.gypi
3223 error gyp verb gyp gyp format was not specified; forcing "msvs"
3223 error gyp info spawn C:\Python27\python2.EXE
3223 error gyp info spawn args [
3223 error gyp info spawn args   'C:\\Users\\User\\rd\\node_modules\\node-gyp\\gyp\\gyp_main.py',
3223 error gyp info spawn args   'binding.gyp',
3223 error gyp info spawn args   '-f',
3223 error gyp info spawn args   'msvs',
3223 error gyp info spawn args   '-G',
3223 error gyp info spawn args   'msvs_version=2015',
3223 error gyp info spawn args   '-I',
3223 error gyp info spawn args   'C:\\Users\\User\\rd\\node_modules\\node-sass\\build\\config.gypi',
3223 error gyp info spawn args   '-I',
3223 error gyp info spawn args   'C:\\Users\\User\\rd\\node_modules\\node-gyp\\addon.gypi',
3223 error gyp info spawn args   '-I',
3223 error gyp info spawn args   'C:\\Users\\User\\.node-gyp\\15.14.0\\include\\node\\common.gypi',
3223 error gyp info spawn args   '-Dlibrary=shared_library',
3223 error gyp info spawn args   '-Dvisibility=default',
3223 error gyp info spawn args   '-Dnode_root_dir=C:\\Users\\User\\.node-gyp\\15.14.0',
3223 error gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\User\\rd\\node_modules\\node-gyp',
3223 error gyp info spawn args   '-Dnode_lib_file=C:\\Users\\User\\.node-gyp\\15.14.0\\<(target_arch)\\node.lib',
3223 error gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\User\\rd\\node_modules\\node-sass',
3223 error gyp info spawn args   '-Dnode_engine=v8',
3223 error gyp info spawn args   '--depth=.',
3223 error gyp info spawn args   '--no-parallel',
3223 error gyp info spawn args   '--generator-output',
3223 error gyp info spawn args   'C:\\Users\\User\\rd\\node_modules\\node-sass\\build',
3223 error gyp info spawn args   '-Goutput_dir=.'
3223 error gyp info spawn args ]
3223 error gyp verb command build []
3223 error gyp verb build type Release
3223 error gyp verb architecture x64
3223 error gyp verb node dev dir C:\Users\User\.node-gyp\15.14.0
3223 error gyp verb found first Solution file build/binding.sln
3223 error gyp verb using MSBuild: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe
3223 error gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe
3223 error gyp info spawn args [
3223 error gyp info spawn args   'build/binding.sln',
3223 error gyp info spawn args   '/nologo',
3223 error gyp info spawn args   '/p:Configuration=Release;Platform=x64'
3223 error gyp info spawn args ]
3223 error gyp ERR! UNCAUGHT EXCEPTION
3223 error gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe ENOENT
3223 error gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
3223 error gyp ERR! stack     at onErrorNT (node:internal/child_process:480:16)
3223 error gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:81:21)
3223 error gyp ERR! System Windows_NT 10.0.19042
3223 error gyp ERR! command "C:\\Users\\User\\scoop\\apps\\nvm\\current\\nodejs\\nodejs\\node.exe" "C:\\Users\\User\\rd\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
3223 error gyp ERR! cwd C:\Users\User\rd\node_modules\node-sass
3223 error gyp ERR! node -v v15.14.0
3223 error gyp ERR! node-gyp -v v3.8.0
3223 error gyp ERR! This is a bug in `node-gyp`.
3223 error gyp ERR! Try to update node-gyp and file an Issue if it does not help:
3223 error gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
3223 error Build failed with error code: 7
3224 verbose exit 1
```

I have node-gyp installed but it's in `C:\Users\user\scoop\persist\nvm\nodejs\v15.14.0\node_modules\npm\node_modules\node-gyp` and am not exactly sure how we're supposed to get at that.

Also after the run `rd/node_modules` is almost empty, looks like it gets cleared on `npm i` failure

**Comment by ericpromislow** [comment]
Need to replace `/usr/local/bin` with something more portable.  I'm fine with ensuring `%HOMEDRIVE%\bin` exists, adding it to the path (if that makes sense the way windows processes aren't hierarchical the way Unix ones are), and linking to them there.

It also complained that it couldn't get kubernetes to work. I ran it again, didn't see the dialog, but the port-forwarding list is empty. Also, without a tray icon, there's no way to see the status.  But running `kubectl` from another command shell, I can see that no context has been set, but there is a `rancher-desktop` context. If I set it, `kubectl get pods -A` gives this error message:

```
PS C:\Users\User\rd> .\resources\win32\bin\kubectl.exe get pods -A
Unable to connect to the server: dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it.
PS C:\Users\User\rd>
```

**Comment by mook-as** [comment]
Hmm, there should be a tray icon (it may be hidden by default on Windows).

I haven't thought about the tools yet (we might want to just add the resources directory to `$PATH`?).

Maybe it's taking a while to download the k3s images? We don't good status reporting yet (#168), but checking for the files would be useful.  They should be in `%LocalAppData%\xdg.cache\rancher-desktop`. (Not sure why the odd path, but that's from the paths package we're using.)

**Comment by jandubois** [comment]
> I'm fine with ensuring `%HOMEDRIVE%\bin` exists, adding it to the path (if that makes sense the way windows processes aren't hierarchical the way Unix ones are), and linking to them there.

I have no idea how the app will be installed, but I would have assumed it will eventually be packaged as an MSI, which will install into an application directory, like `C:\Program Files\Rancher Desktop`, which would be added to the `PATH` and also include the commandline utilities. The Mandalorian says: "It is the way!". Isn't it?

**Comment by jandubois** [comment]
> But running `kubectl` from another command shell, I can see that no context has been set, but there is a `rancher-desktop` context. If I set it, `kubectl get pods -A` gives this error message:
> 
> ```
> PS C:\Users\User\rd> .\resources\win32\bin\kubectl.exe get pods -A
> Unable to connect to the server: dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it.
> PS C:\Users\User\rd>
> ```

Doesn't this just mean that `%KUBECONFIG%` has not been set? Because this is using the default port on localhost (using IPv6) and not an actual address used by k3s.

**Comment by ericpromislow** [comment]
The main problem is that k8s doesn't start up correctly on my windows box. While it's running, `kubectl config get-contexts` reports zero contexts. I should see a context called `rancher-desktop`. 

Possible problems, but not likely:
```


 WARN  Compiled with 2 warnings                                                               friendly-errors 15:11:17


 WARN  in ./src/k8s-engine/k8s.ts                                                             friendly-errors 15:11:17

"export 'ServiceEntry' was not found in './client'                                            friendly-errors 15:11:17
                                                                                              friendly-errors 15:11:17

 WARN  in ./node_modules/openid-client/node_modules/keyv/src/index.js                         friendly-errors 15:11:17

Critical dependency: the request of a dependency is an expression                             friendly-errors 15:11:17
                                                                                              friendly-errors 15:11:17
```

**Comment by ericpromislow** [comment]
Also:
```
No issues found.                                                                                              15:11:17  
refreshInstallState: \usr\local\bin\kubectl doesn't exist                                                               
refreshInstallState: \usr\local\bin\helm doesn't exist                                                                  
refreshInstallState: \usr\local\bin\kubectl doesn't exist                                                               
refreshInstallState: \usr\local\bin\helm doesn't exist                                                                  
Stopped minikube with code 0                                                                                            
Deleting minikube to reset...                                                                                           
Deleted minikube to reset exited with code 0                                                                            
Error creating symlink for \usr\local\bin\kubectl: ENOENT: no such file or directory, symlink 'C:\Users\User\rd\resource
s\win32\bin\kubectl.exe' -> 'C:\usr\local\bin\kubectl'                                                                  
Error creating symlink for \usr\local\bin\helm: ENOENT: no such file or directory, symlink 'C:\Users\User\rd\resources\w
in32\bin\helm.exe' -> 'C:\usr\local\bin\helm'                                                                           
Kubernetes was unable to start with exit code: undefined                                                                
```

**Comment by ericpromislow** [comment]
Another error seen at startup:
```

(node:1196) UnhandledPromiseRejectionWarning: Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: IP: 172.25.212.134 is not in the cert's list: 10.43.0.1, 127.0.0.1, 172.25.221.243
    at Object.checkServerIdentity (tls.js:288:12)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1494:27)
    at TLSSocket.emit (events.js:310:20)
    at TLSSocket._finishInit (_tls_wrap.js:927:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:697:12)
(node:1196) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To termina
```
 [cutoff at end actually happened]

**Comment by mook-as** [comment]
> Another error seen at startup:
> 
> ```
> 
> (node:1196) UnhandledPromiseRejectionWarning: Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: IP: 172.25.212.134 is not in the cert's list: 10.43.0.1, 127.0.0.1, 172.25.221.243

That one is expected; the k3s cert needs fixing.  But that shouldn't affect getting a cluster up, for now.

**Review by ericpromislow — APPROVED** [review]
Code looks fine, and it ran successfully on my WinVM on macOS, so LGTM

**Pull request merged**
