### PR TITLE
Tweak package.json and .eslintrc to work with node 15.8

### PR DESCRIPTION
**Pull request by ericpromislow**
I want to see how the github job runner handles these changes before merging them into main.

### CODE REVIEW

**Review by mook-as — CHANGES_REQUESTED** [review]
I'd prefer not changing the eslint configs we're copying from dashboard.  If necessary, we can tack things to the end of the file.

I cannot reproduce the issues, using the [`node/buster` docker image](https://hub.docker.com/_/node) (node v15.8.0 and npm 7.5.1; had to install [canvas dependencies](https://www.npmjs.com/package/canvas) first).

**Comment by ericpromislow** [comment]
Moved the changes to the end of the file, and they're better commented now.

I'm blocked without these changes. If this PR works for everyone else, and we can't figure out the unicorn problem here, I recommend accepting it.

**Comment by mook-as** [comment]
I believe the actual issue is identified in #125 — some nested dependency shipped a new version that was broken 🎉

**Comment by ericpromislow** [comment]
No longer needed thx to PR #125

**Pull request closed without merging**
